runtime: custom
env: flex

runtime_config:
  document_root: public

env_variables:
  APP_ENV: production
  APP_KEY: "base64:22eqQFbXr2PEvrjViF0e7EIdzRkIqjnQfU5IOQTl+dQ="
  APP_STORAGE: /tmp
  APP_DEBUG: true
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  LOG_CHANNEL: stderr
  APP_URL: "https://tn360-lqd25ixbvq-ew.a.run.app"

  DB_CONNECTION: mysql
  DB_HOST: /cloudsql/tn-421315:europe-west1:tn360
  DB_PORT: 3306
  DB_DATABASE: "tn360"
  DB_USERNAME: "tn360"
  DB_PASSWORD: "Kr,Lr}&~GXa?~7|Y"

beta_settings:
  cloud_sql_instances: "tn-421315:europe-west1:tn360"

# Ensure Authorization header is passed
handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      Authorization: "Bearer"

# Entry point to install dependencies and optimize the autoloader
entrypoint: composer install --no-dev --optimize-autoloader

# Force HTTPS redirects in production
automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 2

network:
  session_affinity: true # Enable sticky sessions if needed
  forwarded_ports:
    - 443 # Forward HTTPS port

